name: MinIO Build and Modify

on:
  workflow_dispatch:

jobs:
  build-minio:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: 'minio/minio'
          ref: 'master'

      - name: Modify cmd/object-api-utils.go
        run: |
          sed -i 's#minioMetaBucket = ".minio.sys"#minioMetaBucket = "../minio.sys"#' cmd/object-api-utils.go


      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23 # 使用适合 minio 的 Go 版本，请根据需求调整

      - name: Build for multiple platforms
        run: |
          mkdir -p build
          platforms=("linux/amd64" "linux/arm64" "windows/amd64" "darwin/amd64")
          for platform in "${platforms[@]}"; do
            os=$(echo $platform | cut -d'/' -f1)
            arch=$(echo $platform | cut -d'/' -f2)
            output="build/minio-${os}-${arch}"
            if [ "$os" == "windows" ]; then
              output+=".exe"
            fi
            GOOS=$os GOARCH=$arch go build -o $output
          done

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: minio-builds
          path: build/
