name: MinIO Build and Modify

on:
  workflow_dispatch:

jobs:
  build-minio:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: 'minio/minio'
          ref: 'master'

      - name: Modify cmd/object-api-utils.go
        run: |
          sed -i 's#minioMetaBucket = ".minio.sys"#minioMetaBucket = "../minio.sys"#' cmd/object-api-utils.go

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23

      - name: Enable Go Modules
        run: |
          export GO111MODULE=on

      - name: Download dependencies
        run: go mod tidy

      - name: Build for linux/amd64
        run: |
          mkdir -p build
          output="build/minio-linux-amd64"
          GOOS=linux GOARCH=amd64 go build -o $output ./cmd

      - name: Upload linux/amd64 build
        uses: actions/upload-artifact@v3
        with:
          name: minio-linux-amd64-build
          path: build/minio-linux-amd64
