name: MinIO Build and Modify

on:
  workflow_dispatch:

jobs:
  build-minio:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: 'minio/minio'
          ref: 'master'

      - name: Modify cmd/object-api-utils.go
        run: |
          sed -i 's#minioMetaBucket = ".minio.sys"#minioMetaBucket = "../minio.sys"#' cmd/object-api-utils.go

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23

      - name: Enable Go Modules
        run: |
          export GO111MODULE=on

      - name: Download dependencies
        run: go mod tidy

      - name: Build for multiple platforms
        run: |
          mkdir -p build
          platforms=("linux/amd64" "linux/arm64" "windows/amd64" "darwin/amd64")
          for platform in "${platforms[@]}"; do
            os=$(echo $platform | cut -d'/' -f1)
            arch=$(echo $platform | cut -d'/' -f2)
            output="build/minio-${os}-${arch}"
            if [ "$os" == "windows" ]; then
              output+=".exe"
            fi
            GOOS=$os GOARCH=$arch go build -o $output ./cmd
          done

      - name: Upload all builds
        uses: actions/upload-artifact@v3
        with:
          name: minio-builds
          path: |
            build/minio-linux-amd64
            build/minio-linux-arm64
            build/minio-darwin-amd64
            build/minio-windows-amd64.exe
